ARG PY_VERSION="3.5"
ARG DIST="slim-stretch"

FROM python:${PY_VERSION}-${DIST}

WORKDIR /modeldb-basic

COPY requirements* ./

RUN pip install -r requirements.txt -r requirements-dev.txt && \
    rm -rf /root/.cache

ADD . .
